# SEPARATE ALMOST EMPTY MAIN FILE
# NEEDED TO CIRCUMVENT THE IMPORT
# ISSUE:

# GAME HANDLER AND GUI MODULES
# WILL RAISE AN CIRCULAR ERROR
# WITHOUT THIS MAIN FILE!

# PYLINT FALSELY RAISES AN UNUSED IMPORT
# NOTICE HERE

import gui  # pylint: disable=unused-import
